--1
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

--2
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "FULL NAME", (EXTRACT(YEAR FROM J.END_DATE)-EXTRACT(YEAR FROM J.START_DATE)) AS "TOTAL YEARS"
FROM EMPLOYEES E, JOB_HISTORY J
WHERE E.EMPLOYEE_ID = J.EMPLOYEE_ID;

--3
SELECT MANAGER_ID,MIN(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL GROUP BY MANAGER_ID HAVING MIN(SALARY)!=(2000) ORDER BY MIN(SALARY) DESC;
                     
                     
--4
SELECT E.FIRST_NAME
FROM EMPLOYEES E;


--5
SELECT D.DEPARTMENT_NAME, AVG(SALARY),COUNT(E.EMPLOYEE_ID)
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.EMPLOYEE_ID = D.DEPARTMENT_ID AND E.COMMISSION_PCT IS NOT NULL
GROUP BY D.DEPARTMENT_NAME;

--6
SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN (SELECT MIN(SALARY)FROM EMPLOYEES) AND 2500; 

--7

SELECT MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID BETWEEN 100 AND 200;


--8
SELECT E.EMPLOYEE_ID, E.FIRST_NAME || E.LAST_NAME AS "NAME", E.JOB_ID, E.SALARY
FROM EMPLOYEES E
WHERE E.SALARY > (SELECT SALARY
                  FROM EMPLOYEES
                  WHERE UPPER(JOB_ID) = 'PU_MAN') AND UPPER(E.JOB_ID) <> 'PU_MAN';

--9
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(SELECT MANAGER_ID FROM EMPLOYEES);

--10
SELECT D.DEPARTMENT_ID, SUM(E.SALARY),COUNT(E.EMPLOYEE_ID)
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID HAVING COUNT(E.EMPLOYEE_ID)>=1;

--11

--ASSUMING THAT HIRE DATE AND START DATE ARE IN SYNC AND THAT NO EMPLOYEE JOINS DURING THE END_DATE AND START DATE
SELECT E.*
FROM EMPLOYEES E, JOB_HISTORY J
WHERE E.EMPLOYEE_ID = J.EMPLOYEE_ID AND E.HIRE_DATE <> J.START_DATE;

--12
SELECT EMPLOYEE_ID, FIRST_NAME || LAST_NAME AS "NAME", SALARY, ROUND(SALARY -(SELECT AVG(SALARY) FROM EMPLOYEES)) AS "AVG_COMPARE"
FROM EMPLOYEES;


-- COMBINE BOTH OF THEM AND SAVE THE COLUMN AS SALARY_STATUS
(SELECT SALARY AS "HIGH"
FROM EMPLOYEES
WHERE SALARY >(SELECT AVG(SALARY) FROM EMPLOYEES));

SELECT SALARY AS "LOW"
FROM EMPLOYEES WHERE SALARY <(SELECT AVG(SALARY) FROM EMPLOYEES);

--13


--14
SELECT *
FROM EMPLOYEES
WHERE SALARY > 
                (SELECT SALARY 
                FROM EMPLOYEES
                WHERE UPPER(LAST_NAME) = 'OZER');


--15
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS "FULL NAME", (EXTRACT(YEAR FROM J.END_DATE)-EXTRACT(YEAR FROM J.START_DATE)) AS "TOTAL YEARS"
FROM EMPLOYEES E,JOB_HISTORY J
WHERE E.EMPLOYEE_ID = J.EMPLOYEE_ID;
