select * from JOBS;
select MIN_SALARY,MAX_SALARY from JOBS where JOB_TITLE = 'President'; 
select * from EMPLOYEES where SALARY = 20000;
select JOB_ID from EMPLOYEES where SALARY >= 15000;
select EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID from EMPLOYEES where LAST_NAME = 'King';
select  EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID from EMPLOYEES where DEPARTMENT_ID = 50;
select PHONE_NUMBER from EMPLOYEES where DEPARTMENT_ID = 80 AND MANAGER_ID = 100;
select * from EMPLOYEES where FIRST_NAME = 'John' OR FIRST_NAME = 'Neena' OR FIRST_NAME = 'Lency';
select CITY from LOCATIONS WHERE COUNTRY_ID = 'IT';
SELECT CITY FROM LOCATIONS WHERE NOT COUNTRY_ID = 'IN' AND NOT COUNTRY_ID = 'CH';
SELECT JOB_ID FROM JOBS WHERE MIN_SALARY > 8000 AND MIN_SALARY < 15000;
SELECT PHONE_NUMBER FROM EMPLOYEES WHERE DEPARTMENT_ID = 90 AND NOT JOB_ID = 'IT_PROG';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE > '12-Dec-07';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE > '12-Dec-07' AND DEPARTMENT_ID = '100';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE > '12-Dec-07' AND NOT DEPARTMENT_ID = '100';

