--TASK 2
CREATE TABLE JOBS AS SELECT * FROM HR.JOBS WHERE 1=2;
CREATE TABLE JOBS_HISTORY AS SELECT * FROM HR.JOB_HISTORY WHERE 1=2;
ALTER TABLE JOBS ADD PRIMARY KEY (JOB_ID);
ALTER TABLE JOBS_HISTORY ADD PRIMARY KEY (JOB_ID);

--TASK 3
ALTER TABLE JOBS MODIFY JOB_ID INT;
ALTER TABLE JOBS_HISTORY MODIFY JOB_ID INT;

--TASK 4
ALTER TABLE JOBS_HISTORY ADD CONSTRAINT JOB_FK FOREIGN KEY(JOB_ID) REFERENCES JOBS (JOB_ID);

--TASK 5
INSERT INTO JOBS VALUES (100,'TA',100,1000);
INSERT INTO JOBS_HISTORY VALUES ('200','9-SEP-2022','10-SEP-2023',100,13);

--TASK 6
ALTER TABLE JOBS ADD (NATURE VARCHAR(20));

--TASK 7
CREATE TABLE EMPLOYEES AS SELECT * FROM HR.EMPLOYEES WHERE 1=2;
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID);

--TASK 8
--Check This
ALTER TABLE JOBS_HISTORY ADD CONSTRAINT EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID);

--TASK 9
ALTER TABLE JOBS DROP COLUMN NATURE;

--TASK 10
ALTER TABLE EMPLOYEES ADD CONSTRAINT CAPITAL_NAME CHECK (FIRST_NAME = UPPER(FIRST_NAME));

--Task 11
ALTER TABLE EMPLOYEES ADD CONSTRAINT SALARY_DIFF UNIQUE (SALARY);

--Task 12
ALTER TABLE EMPLOYEES ADD CONSTRAINT PHONE_EMPTY CHECK (PHONE_NUMBER IS NOT NULL); 
--OR
ALTER TABLE EMPLOYEES MODIFY PHONE_NUMBER VARCHAR(20) NOT NULL;

--Task 13
INSERT INTO EMPLOYEES VALUES (105,'MOHSIN','MIRZA','K200353@NU.EDU.PK',3317534906,'9-SEP-2022',202,800,0,303,404);

--Task 14
UPDATE EMPLOYEES SET SALARY=2000 WHERE EMPLOYEE_ID=105 AND SALARY<1000;

--Task 15
ALTER TABLE EMPLOYEES ADD PRIMARY KEY(EMPLOYEE_ID,JOB_ID);
--A table cant have 2 primary keys 

--Task 16
CREATE UNIQUE INDEX INDX_JOB_ID ON JOBS_HISTORY(JOB_ID);
--Task 17
TRUNCATE TABLE EMPLOYEES;